<?xml version="1.0"?>
<robot name="robot_hand" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find tesollo)/urdf/materials.xacro" />

  <xacro:property name="robot_base_radius" value="0.64"  />
  <xacro:property name="robot_base_length" value="0.405" />

  <xacro:property name="finger_link0_width" value="0.196"/>
  <xacro:property name="finger_link0_length" value="0.358" />
  <xacro:property name="finger_link0_height" value="0.284" />

  <xacro:property name="finger_link1_width" value="0.196" />
  <xacro:property name="finger_link1_length" value="0.284" />
  <xacro:property name="finger_link1_height" value="0.358" />

  <xacro:property name="finger_link3_width" value="0.196" />
  <xacro:property name="finger_link3_length" value="0.284" />
  <xacro:property name="finger_link3_height" value="0.358" />

  <xacro:property name="PI" value="3.14"/>
  
  <!-- <link name="world"/>
  
  <joint name="world_base_footprint_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="world"/>
    <child link="base_footprint"/>
  </joint>

  <link name="base_footprint" />

  <joint name="base_footprint_link_joint" type="fixed">
    <origin xyz="0 0 ${robot_base_length/2}" rpy="0 0 0" />
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link"/>
  </joint> -->
  
  <!-- Robot hand base-->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${-1*PI/2}"/>
      <geometry>
        <mesh filename="../meshes/base.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="grey"/>
    </visual>
  </link>

  <!-- finger_1 -->
  <joint name="finger_1_joint0" type="fixed">
    <origin xyz="${finger_link0_width/2} 0 ${finger_link0_height/2}" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="finger_1_link0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- motor 1 -->
  <link name="finger_1_link0">   
    <visual>
      <origin xyz="0 0 ${finger_link0_height/2}" rpy="0 0 ${1*PI/2}"/>
      <geometry>
        <mesh filename="../meshes/finger0.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="orange"/>
    </visual>
  </link>
  
  <joint name="finger_1_joint1" type="revolute">
    <origin xyz="0.07 0 ${finger_link1_length}" rpy="0 0 0" />
    <parent link="finger_1_link0"/>
    <child link="finger_1_link1"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000" lower="-0.785" upper="0.785" velocity="5.027"/>
  </joint>

  <!-- motor 2 -->
  <link name="finger_1_link1">
    <visual>
      <origin xyz="0 0 ${finger_link1_height/2 + 0.04}" rpy="0 0 ${1*PI/2}"/>
      <geometry>
        <mesh filename="../meshes/finger1.stl" scale="0.01 0.01 0.01"/>
        <!-- <cylinder radius="${finger_link1_radius}" length="${finger_link1_length}" /> -->
      </geometry>
      <material name="red"/>
    </visual>
  </link>

  <joint name="finger_1_joint2" type="revolute">
    <origin xyz="${finger_link1_width/2+0.025} +0.005 ${finger_link1_height-0.065}" rpy="0 ${1*PI/2} 0" />    <!-- add offset -->
    <parent link="finger_1_link1"/>
    <child link="finger_1_link2"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000" lower="-1.57" upper="1.57" velocity="5.027"/>
  </joint>

  <!-- link -->
  <link name="finger_1_link2">
    <visual>
      <origin xyz="-0.05 -0.01 0.1" rpy="0 0 ${1*PI/2}"/> <!-- add offset -->
      <geometry>
        <mesh filename="../meshes/link.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  <!-- motor 3 -->
  <joint name="finger_1_joint3" type="revolute">
    <origin xyz="-0.1 0 0.2" rpy="${1*PI/2} 0 0" />
    <parent link="finger_1_link2"/>
    <child link="finger_1_link3"/>
    <limit effort="1000" lower="0" upper="1.57" velocity="5.027"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="finger_1_link3">
    <visual>
      <origin xyz="0 ${finger_link3_length/2} 0" rpy="${-1*PI/2} ${1*PI/2} 0"/>
      <geometry>
        <mesh filename="../meshes/finger2.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>

  <!-- motor 4 -->
  <joint name="finger_1_joint4" type="revolute">
    <origin xyz="0 ${finger_link3_height + 0.087} 0" rpy="0 0 0" />
    <parent link="finger_1_link3"/>
    <child link="finger_1_link4"/>
    <limit effort="1000" lower="0" upper="1.57" velocity="5.027"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="finger_1_link4">
    <visual>
      <origin xyz="-0.01 0.22 -0.01" rpy="${-1*PI/2} ${1*PI/2} 0"/>
      <geometry>
        <mesh filename="../meshes/finger3.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="green"/>
    </visual>
  </link>


  <!-- finger_2 -->
  <joint name="finger_2_joint0" type="fixed">
    <origin xyz="-0.05 ${-1*finger_link0_width} ${finger_link0_height/2}" rpy="0 0 ${PI}" />
    <parent link="base_link"/>
    <child link="finger_2_link0"/>
    <axis xyz="0 0 1"/>
  </joint>


  <link name="finger_2_link0">
    <visual>
      <origin xyz="0 0 ${finger_link0_height/2}" rpy="0 0 ${1*PI/2}"/>
      <geometry>
        <mesh filename="../meshes/finger0.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="orange"/>
    </visual>
  </link>

  <joint name="finger_2_joint1" type="revolute">
    <origin xyz="0.07 0 ${finger_link1_length}" rpy="0 0 0" />
    <parent link="finger_2_link0"/>
    <child link="finger_2_link1"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000" lower="0" upper="0.785" velocity="5.027"/>
  </joint>

  <!-- motor 2 -->
  <link name="finger_2_link1">
    <visual>
      <origin xyz="0 0 ${finger_link1_height/2 + 0.04}" rpy="0 0 ${1*PI/2}"/>
      <geometry>
        <mesh filename="../meshes/finger1.stl" scale="0.01 0.01 0.01"/>
        <!-- <cylinder radius="${finger_link1_radius}" length="${finger_link1_length}" /> -->
      </geometry>
      <material name="red"/>
    </visual>
  </link>

  <joint name="finger_2_joint2" type="revolute">
    <origin xyz="${finger_link1_width/2+0.025} +0.005 ${finger_link1_height-0.065}" rpy="0 ${1*PI/2} 0" />    <!-- add offset -->
    <parent link="finger_2_link1"/>
    <child link="finger_2_link2"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000" lower="-1.57" upper="1.57" velocity="5.027"/>
  </joint>

  <!-- link -->
  <link name="finger_2_link2">
    <visual>
      <origin xyz="-0.05 -0.01 0.1" rpy="0 0 ${1*PI/2}"/> <!-- add offset -->
      <geometry>
        <mesh filename="../meshes/link.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  <!-- motor 3 -->
  <joint name="finger_2_joint3" type="revolute">
    <origin xyz="-0.1 0 0.2" rpy="${1*PI/2} 0 0" />
    <parent link="finger_2_link2"/>
    <child link="finger_2_link3"/>
    <limit effort="1000" lower="0" upper="1.57" velocity="5.027"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="finger_2_link3">
    <visual>
      <origin xyz="0 ${finger_link3_length/2} 0" rpy="${-1*PI/2} ${1*PI/2} 0"/>
      <geometry>
        <mesh filename="../meshes/finger2.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>

  <!-- motor 4 -->
  <joint name="finger_2_joint4" type="revolute">
    <origin xyz="0 ${finger_link3_height + 0.087} 0" rpy="0 0 0" />
    <parent link="finger_2_link3"/>
    <child link="finger_2_link4"/>
    <limit effort="1000" lower="0" upper="1.57" velocity="5.027"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="finger_2_link4">
    <visual>
      <origin xyz="-0.01 0.22 -0.01" rpy="${-1*PI/2} ${1*PI/2} 0"/>
      <geometry>
        <mesh filename="../meshes/finger3.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="green"/>
    </visual>
  </link>


  <!-- finger_3 -->
  <joint name="finger_3_joint0" type="fixed">
    <origin xyz="-0.05 ${1*finger_link0_width} ${finger_link0_height/2}" rpy="0 0 ${PI}" />
    <parent link="base_link"/>
    <child link="finger_3_link0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="finger_3_link0">
    <visual>
      <origin xyz="0 0 ${finger_link0_height/2}" rpy="0 0 ${1*PI/2}"/>
      <geometry>
        <mesh filename="../meshes/finger0.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="orange"/>
    </visual>
  </link>

  <joint name="finger_3_joint1" type="revolute">
    <origin xyz="0.07 0 ${finger_link1_length}" rpy="0 0 0" />
    <parent link="finger_3_link0"/>
    <child link="finger_3_link1"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000" lower="-0.785" upper="0" velocity="5.027"/>
  </joint>

  <!-- motor 2 -->
  <link name="finger_3_link1">
    <visual>
      <origin xyz="0 0 ${finger_link1_height/2 + 0.04}" rpy="0 0 ${1*PI/2}"/>
      <geometry>
        <mesh filename="../meshes/finger1.stl" scale="0.01 0.01 0.01"/>
        <!-- <cylinder radius="${finger_link1_radius}" length="${finger_link1_length}" /> -->
      </geometry>
      <material name="red"/>
    </visual>
  </link>

  <joint name="finger_3_joint2" type="revolute">
    <origin xyz="${finger_link1_width/2+0.025} +0.005 ${finger_link1_height-0.065}" rpy="0 ${1*PI/2} 0" />    <!-- add offset -->
    <parent link="finger_3_link1"/>
    <child link="finger_3_link2"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000" lower="-1.57" upper="1.57" velocity="5.027"/>
  </joint>

  <!-- link -->
  <link name="finger_3_link2">
    <visual>
      <origin xyz="-0.05 -0.01 0.1" rpy="0 0 ${1*PI/2}"/> <!-- add offset -->
      <geometry>
        <mesh filename="../meshes/link.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  <!-- motor 3 -->
  <joint name="finger_3_joint3" type="revolute">
    <origin xyz="-0.1 0 0.2" rpy="${1*PI/2} 0 0" />
    <parent link="finger_3_link2"/>
    <child link="finger_3_link3"/>
    <limit effort="1000" lower="0" upper="1.57" velocity="5.027"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="finger_3_link3">
    <visual>
      <origin xyz="0 ${finger_link3_length/2} 0" rpy="${-1*PI/2} ${1*PI/2} 0"/>
      <geometry>
        <mesh filename="../meshes/finger2.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>

  <!-- motor 4 -->
  <joint name="finger_3_joint4" type="revolute">
    <origin xyz="0 ${finger_link3_height + 0.087} 0" rpy="0 0 0" />
    <parent link="finger_3_link3"/>
    <child link="finger_3_link4"/>
    <limit effort="1000" lower="0" upper="1.57" velocity="5.027"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="finger_3_link4">
    <visual>
      <origin xyz="-0.01 0.22 -0.01" rpy="${-1*PI/2} ${1*PI/2} 0"/>
      <geometry>
        <mesh filename="../meshes/finger3.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="green"/>
    </visual>
  </link>


  <!-- hand palm -->
  <joint name="palm_joint" type="fixed">
    <origin xyz="0 0 0.7" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="palm_link"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="palm_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${-1 * PI/2}"/>
      <geometry>
        <mesh filename="../meshes/housing.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>


</robot>